import html
import sys
import smtplib
import os
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from groq import Groq


def read_required_file(path: Path) -> str:
    path = Path(path)
    if not path.exists():
        print(f"ERROR: Required file not found: {path}", file=sys.stderr)
        sys.exit(1)
    content = path.read_text(encoding="utf-8").strip()
    if not content:
        print(f"ERROR: Required file is empty: {path}", file=sys.stderr)
        sys.exit(1)
    return content


def load_past_posts(past_posts_dir: Path) -> list[str]:
    past_posts_dir = Path(past_posts_dir)
    if not past_posts_dir.exists():
        return []
    txt_files = sorted(past_posts_dir.glob("*.txt"), reverse=True)[:3]
    result = []
    for f in txt_files:
        result.append(f"--- {f.name} ---\n{f.read_text(encoding='utf-8').strip()}")
    return result


def build_prompt(template: str, notes: str, past_posts: list[str]) -> str:
    if "{notes}" not in template or "{past_posts}" not in template:
        print("ERROR: prompt_template.txt must contain {notes} and {past_posts} placeholders.", file=sys.stderr)
        sys.exit(1)
    past_block = "\n\n".join(past_posts) if past_posts else "(No past posts yet)"
    return template.replace("{past_posts}", past_block).replace("{notes}", notes)


def generate_post(prompt: str) -> str:
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=400,
        temperature=0.8,
    )
    post = response.choices[0].message.content.strip()
    if not post:
        print("ERROR: Groq returned an empty response.", file=sys.stderr)
        sys.exit(1)
    word_count = len(post.split())
    print(f"Generated post: {word_count} words")
    return post


def build_html_email(post: str, date_str: str) -> str:
    escaped_post = html.escape(post).replace("\n", "<br>")
    escaped_date = html.escape(date_str)
    return f"""<!DOCTYPE html>
<html>
<body style="font-family: Georgia, serif; max-width: 600px; margin: 40px auto; color: #222; line-height: 1.7;">
  <h2 style="color: #0077b5;">LinkedIn Post Draft — {escaped_date}</h2>
  <div style="background: #f9f9f9; border-left: 4px solid #0077b5; padding: 20px 24px; border-radius: 4px; white-space: pre-wrap;">
{escaped_post}
  </div>
  <p style="color: #888; font-size: 0.85em; margin-top: 24px;">
    Generated by linkedin-auto-post · Edit and post manually on LinkedIn
  </p>
</body>
</html>"""


def send_email(post: str, date_str: str) -> None:
    gmail_user = os.environ["GMAIL_USER"]
    gmail_password = os.environ["GMAIL_APP_PASSWORD"]
    to_email = os.environ["TO_EMAIL"]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"LinkedIn Post Draft — {date_str}"
    msg["From"] = gmail_user
    msg["To"] = to_email
    msg.attach(MIMEText(post, "plain"))
    msg.attach(MIMEText(build_html_email(post, date_str), "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(gmail_user, gmail_password)
        server.sendmail(gmail_user, to_email, msg.as_string())
    print(f"Email sent to {to_email}")


def archive_post(post: str, past_posts_dir: Path, date_str: str) -> Path:
    past_posts_dir = Path(past_posts_dir)
    past_posts_dir.mkdir(exist_ok=True)
    out = past_posts_dir / f"{date_str}.txt"
    if out.exists():
        print(f"WARNING: Archive file already exists, skipping write: {out}", file=sys.stderr)
        return out
    out.write_text(post, encoding="utf-8")
    print(f"Archived to {out}")
    return out


def main():
    root = Path(__file__).parent
    notes = read_required_file(root / "notes.md")
    template = read_required_file(root / "prompt_template.txt")
    past_posts = load_past_posts(root / "past_posts")

    prompt = build_prompt(template, notes, past_posts)
    post = generate_post(prompt)

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    send_email(post, date_str)
    archive_post(post, root / "past_posts", date_str)


if __name__ == "__main__":
    main()
